### ISSUE TITLE
Add the fce to the advanced interface table

### ISSUE THREAD

**Issue by robbertdol** [quintel/etmodel#186]
```
fce:
  fce_coal:
    :input_elements:
    - coal_from_south_africa_share
    - coal_from_north_america_share
    - coal_from_australia_share
    - coal_from_eastern_europe_share
    - coal_from_russia_share
    - coal_from_south_america_share
    - coal_from_east_asia_share
    - coal_from_western_europe_share
    :output_elements:
    - 100_fuel_chain_emissions
  fce_gas:
    :input_elements:
    - gas_from_nederlands_share
    - gas_from_russia_share
    - gas_from_norway_share
    - gas_from_algeria_share
    - gas_from_middle_east_share
    :output_elements:
    - 100_fuel_chain_emissions
  fce_biomass:
    :input_elements: []
    :output_elements:
    - 100_fuel_chain_emissions
  fce_greengas:
    :input_elements: []
    :output_elements:
    - 100_fuel_chain_emissions
  fce_uranium:
    :input_elements:
    - uranium_from_kazachstan_share
    - uranium_from_australia_share
    - uranium_from_canada_share
    :output_elements:
    - 100_fuel_chain_emissions
```
