### ISSUE TITLE
Allow charts to set a custom downsampleWith value

### ISSUE THREAD

**Issue by antw** [quintel/etmodel#3419]
Currently we determine how to downsample curve charts using the [`downsampleWith` attribute](https://github.com/quintel/etmodel/blob/c9e84f73b496507e4463025efdbc6d7766ef7d0e/app/assets/javascripts/lib/views/d3_yearly_chart_view.coffee#L11) on the chart class. Each chart class (type) may customise this value.

However there are cases where it would make sense for individual charts to be able to customise this value. It may make sense to use `downsampleWith: "max"` for a hydrogen load chart, but `downsampleWith: "mean"` for a "storage of heat" chart.

I would suggest that we add an attribute to output elements: either a `downsample_with` so that each chart can set a custom value, or a `display_options` hash, which might open the door to further customisations later:

```yaml
- key: chart_one
  type: demand_curve
  display_options:
    downsample_with: mean
  # ...

- key: chart_two
  type: demand_curve
  display_options:
    downsample_with: max
  # ...
```

See: https://github.com/quintel/etmodel/issues/2867
See: https://github.com/quintel/etmodel/pull/3359
