### ISSUE TITLE
Hybrid heat pump table should be added to the chart list again

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3424]
Somehow the HHP table (with input shares of gas, hydrogen and electricity) is not shown in the chart list anymore. Here is the migration that should have added the table: https://github.com/quintel/etmodel/blob/master/db/migrate/20200331112350_add_table_hybrid_heat_pump.rb

**Comment by noracato** [comment]
I think this one didn't make it to ymodel. This is the info about the table I could dig up to add to [config/interface/output_elements/demand_households.yml](https://github.com/quintel/etmodel/blob/master/config/interface/output_elements/demand_households.yml):

```
- key: hybrid_heat_pump
  output_element_type_name: html_table
  group: Demand
  sub_group: households
  related_output_element_key: household_space_heater_hhp_hourly_demand
  hidden: false
  unit:
  min_axis_value:
  dependent_on:
```

However I'm not sure about the unit or dependencies, do you know @marliekeverweij?
