### ISSUE TITLE
Creating saved_scenarios links for featured scenarios and removing them as presets from ETSource

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3434]
As just discussed in the team meeting today, we would like to create saved_scenarios-links for featured scenarios and remove the ad-files from ETSource. It would be nice to combine this improvement with the featured scenario update, on which @MartLubben is working at the moment.

The reasons for this and possible approaches can be read in this BC todo: https://3.basecamp.com/3797409/buckets/16975857/todos/2641700236 As not everybody has been added to this project I'll add Anthony's comment below.
@noracato @antw I have some questions for you:

- Which approach do you prefer?
- How much time do you think this would take?
- Is it possible to combine this @MartLubben 's update (to pick this up the coming 1,5 week) or should we not hurry?

@antw's messages on BC:
_______
Move featured scenarios to be a saved_scenario links has two advantages:

1. It would make it easier to migrate these scenarios, since they'd be updated by the normal DB migration.
2. We can represent more complex scenarios. Presets are capable of storing everything a database scenario can, except uploaded curves. Having one way of doing things (the DB) avoids this problem.

There is one small gotcha: we need to be sure the scenario IDs are the same for production and staging, so that the references in ETModel work correctly in both environments. That, or we need a way to configure which scenarios are shown in the preset scenarios list by environment.

I'm imagining a YAML file like:
```
- national_scenarios:
  # 100% duurzame energie in 2030
  - production: 1000  # ID of the scenario on production ETE
    staging: 2212     # ID of the scenario on staging ETE
  # Net voor de Toekomst - Generieke sturing
  - production: 1001
    staging: 2213
  # ...
- scenarios_for_provinces_and_regions:
  # ..
```
An alternative might be to add a new table to ETEngine: "featured_scenarios" with a couple of columns:

- scenario_id – Self-explanatory
- key – A unique (string) key which identifies the scenario.

ETEngine would still be responsible for sending the list of featured scenarios to ETModel (as it does today with presets), rather than ETModel defining them in a config file. ScenarioController#create/Scenario would need to be able to receive the featured scenario "key" to create a clone of the preset.
