### ISSUE TITLE
Presets II3050 do not give the same scenario when scenario settings from ETEngine are copied to an empty scenario

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#3469]
During testing of difference in presets between BETA and PRO I found that some sliders are not set on the ETEngine-version of the preset. 

**Approach**
The presets for II3050 are only visible/present on PRO.
To test whether I see differences I openened the presets on PRO and copied scenario-settings of the opened scenario to an empty scenario on BETA.

**Findings**
For all scenario's three sliders are not explicitly set on the created scenario's on BETA:

- Households heating oil and coal: should be 0, the visible shares add up to 100%, but it seems that these sliders which are in the front end invisible are still on their default value
- Industry Refineries hydrogen: is 0 in all scenario's on Beta and non-zero in all scenario's on live. So the share-sliders on BETA to not add up to 100%.

**Conclusion**
I am unsure whether this will be an issue after the deploy. The presets on PRO work fine right now, so most probably this will remain the case with the deploy. Curious what you think about this @antw 

Notifying @marliekeverweij

**Comment by antw** [comment]
This is because copying the user values isn't enough to faithfully reproduce a scenario. There are also hidden values ("balanced values") which ETEngine automatically sets when you move sliders in a scenario (to ensure groups balance to 100).

These values aren't shown in the ETEngine scenario editor, so of course you did not know that these must also be copied. The balanced values for one such II3050 scenario are:

```yaml
---
households_heater_coal_share: 0.0
households_heater_crude_oil_share: 0.0
buildings_space_heater_crude_oil_share: 0.0
buildings_space_heater_coal_share: 0.0
transport_freight_train_using_coal_share: 0.0
industry_chemicals_refineries_burner_hydrogen_share: 80.0
households_collective_chp_biogas_share: 0.0
energy_greengas_gasification_dry_biomass_share: 0.0
```

I'm fairly confident this won't be an issue when we deploy. It adds some weight to the idea that these balanced values should be included in the scenario editor to ensure this confusion doesn't occur again.
