### ISSUE TITLE
New of residences chart table view does not show units

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etmodel#4398]
The chart `number_of_residences_overview` does not properly display the '#' unit that is specified in it's yml file:
```yml
- under_construction: false
  unit: '#'
  percentage: false
  group: Demand
  sub_group: households
  show_point_label: false
  growth_chart: true
  key: number_of_residences_overview
  max_axis_value:
  min_axis_value:
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: mekko
```

Instead, it displays 'undefined':
![Image](https://github.com/user-attachments/assets/e9a2644f-37dc-45ef-8610-3fe1a3b8dbc7)

I have tried changing it to 'number' but this keeps the chart from loading. I therefore expect it to be something that can only be fixed in the front-end code. Could you have a look @louispt1?
