### ISSUE TITLE
Clean up translation files

### ISSUE THREAD

**Issue by dennisquintel** [quintel/etmodel#713]
Please use the following syntax:
- key: only lowercase and with underscores
- value: "In between double quotes."

e.g:

``` yaml
nl:
  meta:
    name: "Energietransitiemodel"
    title: "Energietransitiemodel - Je eigen onafhankelijke, volledige en op feiten gebaseerde energiescenario."
    description: "Maak je eigen, onafhankelijke energiescenario voor 2020 tot 2050. Direct online en zonder kosten."
  home: "Home"
  demand: "Vraag"
  supply: "Aanbod"
  costs: "Kosten"
  policy: "Doelen"
  local_supply: "Lokaal aanbod"
  local_demand: "Lokale Vraag"
```
